DROP TABLE IF EXISTS prompts;
DROP TABLE IF EXISTS diver;

CREATE TABLE diver (
  LeadDiverID INTEGER PRIMARY KEY AUTOINCREMENT,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LeadDiverName TEXT NOT NULL,
  LeadDiverEmail TEXT NOT NULL
);

CREATE TABLE prompts (
  PromptID INTEGER PRIMARY KEY AUTOINCREMENT,
  LeadDiverID int,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DivePlan TEXT NOT NULL,
  Msg TEXT NOT NULL,
  FOREIGN KEY (LeadDiverID) REFERENCES diver(LeadDiverID)
);